#ifndef PROJECT_A_CONSTANTES_H
#define PROJECT_A_CONSTANTES_H

#define NBBOUTONS 3
#define EPSILON 1e-2
#define FPS 60

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define FONT_SIZE 16

#define PLAYER_SIZE 40
#define PLAYER_LIFE 3
#define PLAYER_SPEED 200

#define ENEMY_SIZE 40
#define ENEMY_LIFE 2
#define ENEMY_SPEED 200
#define ENEMY_DMG 1
#define NENEMY_SCORE_REWARD 1

#define BLOC_TYPE 0
#define BLOC_SIZE 40

#define BULLET_SIZE 10
#define BULLET_SPEED 1000
#define PISTOL_TYPE 0
#define PISTOL_DMG 1

#define NB_ENNEMIS 20

#endif //PROJECT_A_CONSTANTES_H
